## <center>CSE 546: Reinforcement Learning</center>
### <center>Prof. Alina Vereshchaka</center>
<!-- ### <center>Fall 2022</center> -->

Welcome to the Assignment 2, Part 1: Introduction to Deep Reinforcement Learning and Neural Networks! The goal of this assignment is to make you comfortable with the application of different Neural Network structures depending on how the Reinforcement Learning environment is set up.

In [ ]:
import cv2

In [ ]:
# Imports
from environment import WumpusWorldEnvironment

# Environment

We will be working with an implementation of the Wumpus World environment. The environment comes from the book "Artificial Intelligence: A Modern Approach" by Stuart J. Russell and Peter Norvig.

### ENVIRONMENT DETAILS:

The environment is a 6 x 6 grid world containing a total of 36 grid blocks.

#### ENVIRONMENT OBJECTS:
The environment consists of the following objects:

1. **Agent** - The agent starts in the grid block at the bottom left corner whose co-ordinates are [0, 0]. The goal of our agent is to collect the Gold while avoiding the Wumpus and the pits.

2. **Wumpus** - The monster which would eat the agent if they are in the same grid block.

3. **Pit** - The agent must avoid falling into the pits.

4. **Gold** - The agent must collect the Gold.

5. **Breeze** - Breeze surrounds the Pits and warn the agent of a Pit in an adjacent grid block.

6. **Stench** - Stench surrounds the Wumpus and warns the agent of the Wumpus in an adjacent grid block.

#### ENVIRONMENT OBSERVATIONS:

Our implementation of the environment provides you with four different types of observations:

1. **Integer** - Integer in the range [0 - 35]. This represents the grid block the agent is in. E.g., if the agent is in the bottom left grid block (starting position) the observation would be 0, if the agent is in the grid block containing the Gold the observation would be 34, if the agent is in the top right grid block the observation would be 35.

2. **Vector** -

    **2.1.** A vector of length 2 representing the agent co-ordinates. The first entry represents the x co-ordinate and the second entry represets the y co-ordinate. E.g., if the agent is in the bottom left grid block (starting position) the observation would be [0, 0], if the agent is in the grid block containing the Gold the observation would be [4, 5], if the agent is in the top right grid block the observation would be [5, 5].
    
    **2.2.** A vector of length 36 representing the one-hot encoding of the integer observation (refer type 1 above). E.g., if the agent is in the bottom left grid block (starting position) the observation would be [1, 0, ..., 0, 0], if the agent is in the grid block containing the Gold the observation would be [0, 0, ..., 1, 0], if the agent is in the top right grid block the observation would be [0, 0, ..., 0, 1].


3. **Image** - Image render of the environment returned as an NumPy array. The image size is 84 * 84 (same size used in the DQN paper). E.g., if the agent is in the bottom right grid block the observation is:

    Observation: (84 * 84)

     [[255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]

     ...

     [255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]]

    Observation type: <class 'numpy.ndarray'>

    Observation Shape: (84, 84)

    Visually, it looks like:
    <img src="./images/environment_render.png" width="500" height="500">
    

4. **Float** - Float in the range [0 - $\infty$] representing the time elapsed in seconds.

#### ENVIRONMENT ACTIONS:

Our implementation of the environment provides you with three different types of actions:

1. **Discrete** - Integer in the range [0 - 3] representing the four actions possible in the environment as follows: 0 - Right 1 - Left 2 - Up 3 - Down.

2. **Multi-Discrete** - Array of length four where each element takes binary values 0 or 1. Array elements represent if we take a particular action. Array element with index 0 corresponds to the right action, index 1 corresponds to the left action, index 2 corresponds to the up action, and index 3 corresponds to the down action. E.g.,
   action = [1, 0, 0, 0] would result in the agent moving right.
   action = [1, 0, 1, 0] would result in the agent moving right and up.
   action = [0, 1, 0, 1] would result in the agent moving left and down.

3. **Continuous** - Float in the range [-1, 1] determining whether the agent will go left, right, up, or down as follows:

    if -1 <= action <= -0.5:
        Go Right.
    elif -0.5 < action <= 0:
        Go Left.
    elif 0 < action <= 0.5:
        Go Up.
    elif 0.5 < action <= 1:
        Go Down.
        
### YOUR TASK IS TO USE A NEURAL NETWORK TO WORK WITH ALL FOUR TYPES OF OBSERVATIONS AND ALL THREE TYPES OF  ACTIONS.
### Note: You don't have to train your agent/neural network. You just have to build the neural network structure that takes the observation as input and produces the desired output with the initial weights.

#### You can use libraries such as PyTorch/TensorFlow/Keras to build your neural networks.

#### <span style="color:red">You cannot use RL libraries that already provide the neural network to you such as Stable-baselines3, Keras-RL, TF agents, Ray RLLib etc.</span>

<img src="./images/wumpus_world_environment.jpg" width="600" height="600">

# START COMPLETING YOUR ASSIGNMENT HERE

## Observation Type - Integer, Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is an integer (refer to environment observations type 1). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_1_64_4.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='discrete')
observation, _ = environment.reset()

# BEGIN_YOUR_CODE
import torch
import torch.nn as nn

class NN_one(nn.Module):
    def __init__(self):
        super(NN_one, self).__init__()
        self.fc1 = nn.Linear(1, 64)
        self.fc2 = nn.Linear(64, 4)
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

DiscreteIntegerenvironment = WumpusWorldEnvironment(observation_type='integer', action_type='discrete')
observation, _ = DiscreteIntegerenvironment.reset()
tensored = torch.tensor([observation], dtype=torch.float32)
model_one = NN_one()
Q_values = model_one(tensored)

print("Observation:", observation) # im guessing first state assigned is always 0
print("Q-values:", Q_values)
# END_YOUR_CODE

Observation: 0
Q-values: tensor([ 0.3028,  0.0493, -0.0847,  0.1281], grad_fn=<ViewBackward0>)


## Observation Type - Vector (2.1), Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a vector of length 2 (refer to environment observations type 2.1). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_2_64_4.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='vector', action_type='discrete')
observation, _ = environment.reset()

# BEGIN_YOUR_CODE
class NN_two(nn.Module):
    def __init__(self):
        super(NN_two, self).__init__()
        self.fc1 = nn.Linear(2, 64) # 2 inputs
        self.fc2 = nn.Linear(64, 4)
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

VectorDiscreteEnvironment = WumpusWorldEnvironment(observation_type='vector', action_type='discrete')
observation, _ = VectorDiscreteEnvironment.reset()
tensored = torch.tensor(observation, dtype=torch.float32).unsqueeze(0)
model_two = NN_two()
Q_values = model_two(tensored)

print("Observation:", observation)
print("Observation shape:", observation.shape)
print("Q-values:", Q_values)
# END_YOUR_CODE

Observation: [0 0]
Observation shape: (2,)
Q-values: tensor([[ 0.1550,  0.1414, -0.1918, -0.3179]], grad_fn=<AddmmBackward0>)


## Observation Type - Vector (2.2), Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a vector of length 36 (refer to environment observations type 2.2). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

**HINT:** Use the integer observation and convert it to a one-hot encoded vector.

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_36_64_4.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='discrete')
observation, _ = environment.reset()

# BEGIN_YOUR_CODE
class NN_three(nn.Module):
    def __init__(self):
        super(NN_three, self).__init__()
        self.fc1 = nn.Linear(36, 64) # 36 inputs
        self.fc2 = nn.Linear(64, 4)  # linear activation for 4 units
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

Thirty6Environment = WumpusWorldEnvironment(observation_type='integer', action_type='discrete')
observation, _ = Thirty6Environment.reset()

# Use the integer observation and convert it to a one-hot encoded vector.
one_hot_encoded = torch.zeros(36)
one_hot_encoded[observation] = 1
model_three = NN_three()
add_dimension = one_hot_encoded
Q_values = model_three(add_dimension)

print("Observation:", one_hot_encoded)
print("Observation shape:", one_hot_encoded.shape)
print("Q-values:", Q_values)
# END_YOUR_CODE

Observation: tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Observation shape: torch.Size([36])
Q-values: tensor([ 0.0176, -0.0003,  0.1508,  0.1241], grad_fn=<ViewBackward0>)


## Observation Type - Image, Action Type - Discrete

The part of the assignment requires you to create a convolutional neural network with one convolutional layer having 128 filters of size 3 x 3, one hidden layer having 64 neurons, and the output layer having 4 neurons. The input to the neural network is an image of size 84 * 84 (refer to environment observations type 3). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/convolutional_neural_network_84x84_128_64_4.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='image', action_type='discrete')
observation, _ = environment.reset()

# BEGIN_YOUR_CODE
class NN_four_Convo(nn.Module):
    def __init__(self):
        super(NN_four_Convo, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=128, kernel_size=3, stride=1, padding=1)
        self.fc1 = nn.Linear(84 * 84 * 128, 64)
        self.fc2 = nn.Linear(64, 4) #linear activation for 4 output units

    def forward(self, x):
        x = torch.relu(self.conv1(x))
        x = x.view(x.size(0), -1)
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

ConvolutionalEnvironment = WumpusWorldEnvironment(observation_type='image', action_type='discrete')
observation, _ = ConvolutionalEnvironment.reset()

# Convert to a tensor
tensored = torch.tensor(observation, dtype=torch.float32)

# Add a dimension for the batch and we might need another as its a 2d convolutional layer
tensored = tensored.unsqueeze(0).unsqueeze(0)
model_four = NN_four_Convo()
# print(model_four) # Checking model architecture
Q_values = model_four(tensored)

print("Observation:", observation)
print("Observation shape:", observation.shape)
print("Q-values:", Q_values)

# END_YOUR_CODE

Observation: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
Observation shape: (84, 84)
Q-values: tensor([[  4.0767,  24.1763, -19.7659, -46.9554]], grad_fn=<AddmmBackward0>)


## Observation Type - Float, Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a float (refer to environment observations type 4). The output of the neural network is an array representing the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_1_64_4.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='float', action_type='discrete')
observation, _ = environment.reset()

# BEGIN_YOUR_CODE
class NN_five(nn.Module):
    def __init__(self):
        super(NN_five, self).__init__()
        self.fc1 = nn.Linear(1, 64)
        self.fc2 = nn.Linear(64, 4)
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

FloatDiscreteEnvironment = WumpusWorldEnvironment(observation_type='float', action_type='discrete')
observation, _ = FloatDiscreteEnvironment.reset()
tensored = torch.tensor([observation])
model_five = NN_five()
Q_values = model_five(tensored)

print("Observation:", observation)
print("Q-values:", Q_values)

# END_YOUR_CODE

Observation: 0.0
Q-values: tensor([ 0.3592,  0.1084, -0.0469, -0.2421], grad_fn=<ViewBackward0>)


## Observation Type - Vector (2.2), Action Type - Multi-Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a vector of length 36 (refer to environment observations type 2.2). The output of the neural network is an array representing the probability of choosing the actions. (If the value of the array element is >=0.5 you will perform the action.) (refer to environment actions type 2).

**HINT:** Use the integer observation and convert it to a one-hot encoded vector.

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_36_64_4_sigmoid.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted action probabilities for the four actions. Print the observation and the action probabilities."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='multi_discrete')
observation, _ = environment.reset()

# BEGIN_YOUR_CODE
class NN_six(nn.Module):
    def __init__(self):
        super(NN_six, self).__init__()
        self.fc1 = nn.Linear(36, 64) # input units 36
        self.fc2 = nn.Linear(64, 4)  #output units : 4
        self.sigmoid = nn.Sigmoid()  # Sigmoid activation for ^^

    def forward(self, x):
        x = torch.relu(self.fc1(x)) #for hidden
        x = self.sigmoid(self.fc2(x))  #for output
        return x



VectorActionEnvironment = WumpusWorldEnvironment(observation_type='integer', action_type='multi_discrete')
observation, _ = VectorActionEnvironment.reset()
one_hot_encoded = torch.zeros(36)
one_hot_encoded[observation] = 1
model_six = NN_six()
action_probablities = model_six(one_hot_encoded)

print("Observation:", observation)
print("Action Probabilities:", action_probablities)

# END_YOUR_CODE

Observation: 0
Action Probabilities: tensor([0.5191, 0.5120, 0.5119, 0.5150], grad_fn=<SigmoidBackward0>)


## Observation Type - Vector (2.2), Action Type - Continuous

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 1 neuron. The input to the neural network is a vector of length 36 (refer to environment observations type 2.2). The output of the neural network is an float in the range [-1, 1] determining the action which will be taken. (refer to environment actions type 3).

**HINT:** Use the integer observation and convert it to a one-hot encoded vector and use the TanH activation function to get the output in the range [-1, 1].

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_36_64_1.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted action. Print the observation and the predicted action."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='continuous')
observation, _ = environment.reset()

# BEGIN_YOUR_CODE
class NN_seven(nn.Module):
    def __init__(self):
        super(NN_seven, self).__init__()
        self.fc1 = nn.Linear(36, 64)
        self.fc2 = nn.Linear(64, 1)
        self.tanh = nn.Tanh()  #tanh activation on just 1 unit

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.tanh(self.fc2(x))
        return x

# Is this correct? Please let us know in feedback. Thank you!

environment = WumpusWorldEnvironment(observation_type='integer', action_type='continuous')
observation, _ = environment.reset()
one_hot_encoded = torch.zeros(36)
one_hot_encoded[observation] = 1
model_six = NN_seven()
actions = model_six(one_hot_encoded)

print("Observation:", one_hot_encoded)
print("Observation shape:", one_hot_encoded.shape)
print("Predicted Action:", actions.item())
# END_YOUR_CODE

Observation: tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Observation shape: torch.Size([36])
Predicted Action: 0.16857248544692993
