## <center>CSE 546: Reinforcement Learning</center>
### <center>Prof. Alina Vereshchaka</center>
<!-- ### <center>Fall 2022</center> -->

Welcome to the Assignment 2, Part 1: Introduction to Deep Reinforcement Learning and Neural Networks! The goal of this assignment is to make you comfortable with the application of different Neural Network structures depending on how the Reinforcement Learning environment is set up.

In [ ]:
# Imports
from environment import WumpusWorldEnvironment 

# Environment

We will be working with an implementation of the Wumpus World environment. The environment comes from the book "Artificial Intelligence: A Modern Approach" by Stuart J. Russell and Peter Norvig. 

### ENVIRONMENT DETAILS:

The environment is a 6 x 6 grid world containing a total of 36 grid blocks. 

#### ENVIRONMENT OBJECTS:
The environment consists of the following objects:

1. **Agent** - The agent starts in the grid block at the bottom left corner whose co-ordinates are [0, 0]. The goal of our agent is to collect the Gold while avoiding the Wumpus and the pits. 

2. **Wumpus** - The monster which would eat the agent if they are in the same grid block.

3. **Pit** - The agent must avoid falling into the pits. 

4. **Gold** - The agent must collect the Gold.

5. **Breeze** - Breeze surrounds the Pits and warn the agent of a Pit in an adjacent grid block.

6. **Stench** - Stench surrounds the Wumpus and warns the agent of the Wumpus in an adjacent grid block.

#### ENVIRONMENT OBSERVATIONS:

Our implementation of the environment provides you with four different types of observations:

1. **Integer** - Integer in the range [0 - 35]. This represents the grid block the agent is in. E.g., if the agent is in the bottom left grid block (starting position) the observation would be 0, if the agent is in the grid block containing the Gold the observation would be 34, if the agent is in the top right grid block the observation would be 35.

2. **Vector** - 

    **2.1.** A vector of length 2 representing the agent co-ordinates. The first entry represents the x co-ordinate and the second entry represets the y co-ordinate. E.g., if the agent is in the bottom left grid block (starting position) the observation would be [0, 0], if the agent is in the grid block containing the Gold the observation would be [4, 5], if the agent is in the top right grid block the observation would be [5, 5].
    
    **2.2.** A vector of length 36 representing the one-hot encoding of the integer observation (refer type 1 above). E.g., if the agent is in the bottom left grid block (starting position) the observation would be [1, 0, ..., 0, 0], if the agent is in the grid block containing the Gold the observation would be [0, 0, ..., 1, 0], if the agent is in the top right grid block the observation would be [0, 0, ..., 0, 1].


3. **Image** - Image render of the environment returned as an NumPy array. The image size is 84 * 84 (same size used in the DQN paper). E.g., if the agent is in the bottom right grid block the observation is:

    Observation: (84 * 84)

     [[255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]

     ...

     [255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]]

    Observation type: <class 'numpy.ndarray'>

    Observation Shape: (84, 84)

    Visually, it looks like:
    <img src="./images/environment_render.png" width="500" height="500">
    

4. **Float** - Float in the range [0 - $\infty$] representing the time elapsed in seconds. 

#### ENVIRONMENT ACTIONS:

Our implementation of the environment provides you with three different types of actions:

1. **Discrete** - Integer in the range [0 - 3] representing the four actions possible in the environment as follows: 0 - Right 1 - Left 2 - Up 3 - Down.

2. **Multi-Discrete** - Array of length four where each element takes binary values 0 or 1. Array elements represent if we take a particular action. Array element with index 0 corresponds to the right action, index 1 corresponds to the left action, index 2 corresponds to the up action, and index 3 corresponds to the down action. E.g., 
   action = [1, 0, 0, 0] would result in the agent moving right.
   action = [1, 0, 1, 0] would result in the agent moving right and up.
   action = [0, 1, 0, 1] would result in the agent moving left and down.

3. **Continuous** - Float in the range [-1, 1] determining whether the agent will go left, right, up, or down as follows:

    if -1 <= action <= -0.5:
        Go Right.
    elif -0.5 < action <= 0:
        Go Left.
    elif 0 < action <= 0.5:
        Go Up.
    elif 0.5 < action <= 1:
        Go Down.
        
### YOUR TASK IS TO USE A NEURAL NETWORK TO WORK WITH ALL FOUR TYPES OF OBSERVATIONS AND ALL THREE TYPES OF  ACTIONS.
### Note: You don't have to train your agent/neural network. You just have to build the neural network structure that takes the observation as input and produces the desired output with the initial weights.

#### You can use libraries such as PyTorch/TensorFlow/Keras to build your neural networks.

#### <span style="color:red">You cannot use RL libraries that already provide the neural network to you such as Stable-baselines3, Keras-RL, TF agents, Ray RLLib etc.</span>

<img src="./images/wumpus_world_environment.jpg" width="600" height="600">

# START COMPLETING YOUR ASSIGNMENT HERE

## Observation Type - Integer, Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is an integer (refer to environment observations type 1). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_1_64_4.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='discrete')
observation, info = environment.reset()

# BEGIN_YOUR_CODE
import torch
import torch.nn as nn

class NN_one(nn.Module):
    def __init__(self):
        super(NN_one, self).__init__()
        self.fc1 = nn.Linear(1, 64)
        self.fc2 = nn.Linear(64, 4)
    
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

DiscremteIntehgerenvironment = WumpusWorldEnvironment(observation_type='integer', action_type='discrete')
observation, _ = DiscremteIntehgerenvironment.reset()

tensored = torch.tensor([observation], dtype=torch.float32)

model_one = NN_one()

Q_values = model_one(tensored)

print("Observation:", observation) # im guessing first state assigned is always 0 
# print("Info", info)
print("Q-values:", Q_values)

# END_YOUR_CODE


## Observation Type - Vector (2.1), Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a vector of length 2 (refer to environment observations type 2.1). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_2_64_4.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='vector', action_type='discrete')
observation, info = environment.reset()

# BEGIN_YOUR_CODE
class NN_two(nn.Module):
    def __init__(self):
        super(NN_two, self).__init__()
        self.fc1 = nn.Linear(2, 64) # 2 inputs
        self.fc2 = nn.Linear(64, 4)
    
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

VectorDiscreteenvironment = WumpusWorldEnvironment(observation_type='vector', action_type='discrete')
observation, _ = VectorDiscreteenvironment.reset()

tensored = torch.tensor(observation, dtype=torch.float32).unsqueeze(0)

model_two = NN_two()
Q_values = model_two(tensored)

print("Observation:", observation)
print("Q-values:", Q_values)

# END_YOUR_CODE

## Observation Type - Vector (2.2), Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a vector of length 36 (refer to environment observations type 2.2). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

**HINT:** Use the integer observation and convert it to a one-hot encoded vector.

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_36_64_4.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='discrete')
observation, info = environment.reset()

# BEGIN_YOUR_CODE
class NN_three(nn.Module):
    def __init__(self):
        super(NN_three, self).__init__()
        self.fc1 = nn.Linear(36, 64) # 36 inputs
        self.fc2 = nn.Linear(64, 4)  # linear activation for 4 units
    
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

thirty6environment = WumpusWorldEnvironment(observation_type='integer', action_type='discrete')
observation, _ = thirty6environment.reset()

# Use the integer observation and convert it to a one-hot encoded vector.
one_hot_encodded_encoded = torch.zeros(36)
one_hot_encodded_encoded[observation] = 1

model_three = NN_three()

add_dimension = one_hot_encodded_encoded
Q_values = model_three(add_dimension)

print("Observation:", observation)
print("Q-values:", Q_values)

# END_YOUR_CODE

## Observation Type - Image, Action Type - Discrete

The part of the assignment requires you to create a convolutional neural network with one convolutional layer having 128 filters of size 3 x 3, one hidden layer having 64 neurons, and the output layer having 4 neurons. The input to the neural network is an image of size 84 * 84 (refer to environment observations type 3). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/convolutional_neural_network_84x84_128_64_4.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='image', action_type='discrete')
observation, info = environment.reset()

# BEGIN_YOUR_CODE
class NN_four_Convo(nn.Module):
    def __init__(self):
        super(NN_four_Convo, self).__init__()
        self.conv1 = nn.Conv2d(1, 128, kernel_size=3, stride=1, padding=1)
        self.fc1 = nn.Linear(84 * 84 * 128, 64)
        self.fc2 = nn.Linear(64, 4) #linear activation for 4 output units 
    
    def forward(self, x):
        x = torch.relu(self.conv1(x))
        x = x.view(x.size(0), -1)  
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

convolutionalenvironment = WumpusWorldEnvironment(observation_type='image', action_type='discrete')
observation, _ = convolutionalenvironment.reset()

# Convert to a tensor
tensord = torch.tensor(observation, dtype=torch.float32)

# Add a dimension for the batch and we might need another as its a 2d convolutional layer
tensord = tensord.unsqueeze(0).unsqueeze(0)

model_four = NN_four_Convo()
Q_values = model_four(tensord)

print("Observation shape:", observation.shape)
print("Q-values:", Q_values)


# END_YOUR_CODE

## Observation Type - Float, Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a float (refer to environment observations type 4). The output of the neural network is an array representing the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_1_64_4.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='float', action_type='discrete')
observation, info = environment.reset()

# BEGIN_YOUR_CODE
class NN_five(nn.Module):
    def __init__(self):
        super(NN_five, self).__init__()
        self.fc1 = nn.Linear(1, 64)
        self.fc2 = nn.Linear(64, 4)
    
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x



floatDisenvironment = WumpusWorldEnvironment(observation_type='float', action_type='discrete')
observation, _ = floatDisenvironment.reset()

tensored = torch.tensor([observation])

model_five = NN_five()
Q_values = model_five(tensored)

print("Observation:", observation)
print("Q-values:", Q_values)

# END_YOUR_CODE

## Observation Type - Vector (2.2), Action Type - Multi-Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a vector of length 36 (refer to environment observations type 2.2). The output of the neural network is an array representing the probability of choosing the actions. (If the value of the array element is >=0.5 you will perform the action.) (refer to environment actions type 2).

**HINT:** Use the integer observation and convert it to a one-hot encoded vector.

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_36_64_4_sigmoid.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted action probabilities for the four actions. Print the observation and the action probabilities."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='multi_discrete')
observation, info = environment.reset()

# BEGIN_YOUR_CODE

class NN_six(nn.Module):
    def __init__(self):
        super(NN_six, self).__init__()
        self.fc1 = nn.Linear(36, 64) # input units 36
        self.fc2 = nn.Linear(64, 4)  #output units : 4
        self.sigmoid = nn.Sigmoid()  # Sigmoid activation for ^^
    
    def forward(self, x):
        x = torch.relu(self.fc1(x)) #for hidden
        x = self.sigmoid(self.fc2(x))  #for output
        return x



Vectoractionenvironment = WumpusWorldEnvironment(observation_type='integer', action_type='multi_discrete')
observation, _ = Vectoractionenvironment.reset()

one_hot_encodded = torch.zeros(36)
one_hot_encodded[observation] = 1

model_six = NN_six()
probabiliti_for_actions = model_six(one_hot_encodded)

print("Observation:", observation)
print("Action Probabilities:", probabiliti_for_actions)

# END_YOUR_CODE

## Observation Type - Vector (2.2), Action Type - Continuous

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 1 neuron. The input to the neural network is a vector of length 36 (refer to environment observations type 2.2). The output of the neural network is an float in the range [-1, 1] determining the action which will be taken. (refer to environment actions type 3).

**HINT:** Use the integer observation and convert it to a one-hot encoded vector and use the TanH activation function to get the output in the range [-1, 1].

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_36_64_1.png">

In [ ]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted action. Print the observation and the predicted action."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='continuous')
observation, info = environment.reset()

# BEGIN_YOUR_CODE

class NN_seven(nn.Module):
    def __init__(self):
        super(NN_seven, self).__init__()
        self.fc1 = nn.Linear(36, 64)
        self.fc2 = nn.Linear(64, 1)
        self.tanh = nn.Tanh()  #tanh activation on just 1 unit
    
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.tanh(self.fc2(x))
        return x

environment = WumpusWorldEnvironment(observation_type='integer', action_type='continuous')
observation, _ = environment.reset()

one_hot_encodded = torch.zeros(36)
one_hot_encodded[observation] = 1

model_six = NN_seven()
actions = model_six(one_hot_encodded)

print("Observation:", observation)
print("Predicted Action:", actions.item())
# END_YOUR_CODE

##Part II [50 points] - Implementing DQN & Solving Various Problems

Source - https://arxiv.org/pdf/1312.5602\

In [ ]:
from collections import deque

In [ ]:
# #Define DQN NN
# class DQN(nn.Module):
#     def __init__(self, input_dimensions, output_dimensions):
#       super(DQN, self).__init__()
#       self.fc1 = nn.Linear(input_dimensions, 64)
#       self.fc2 = nn.Linear(64, 64)
#       self.fc3 = nn.Linear(64, output_dimensions)

#     #same as all the others but relu as its better for DQN
#     def forward(self, x):
#       x = torch.relu(self.fc1(x))
#       x = torch.relu(self.fc2(x))
#       return self.fc3(x)




In [ ]:

# #Initialize replay memory D to capacity N
# class Replay:
#     def __init__(self, capacityN):
#       self.tracker = deque(maxlen=capacityN)
    
#     def push(self, s, a, r, s_, mission_accomplished):
#       transition = (s, a, r, s_, mission_accomplished)
#       self.tracker.append(transition)     # Add the transition to the buffer
    
#     def Sampl(self, batch_len):
#       # Randomly pick a batch of transitions from the buffer
#       transitions = random.sample(self.tracker, batch_len)
#       states = actions = rewards = states_ = missions_accomplished = []

#       for transition in transitions:
#         s, a, r, s_, mission_accomplished = transition
#         states.append(s)
#         actions.append(a)
#         rewards.append(r)
#         states_.append(s_)
#         missions_accomplished.append(mission_accomplished)
      
#       states = np.array(states)
#       actions = np.array(actions)
#       rewards = np.array(rewards, dtype=np.float32)
#       states_ = np.array(states_)
#       missions_accomplished = np.array(missions_accomplished, dtype=np.uint8)

#       return states, actions, rewards, states_, missions_accomplished

    

In [ ]:
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import random
from collections import deque
import gym
import gymnasium as gym
from gymnasium import spaces
import matplotlib.pyplot as plt
import numpy as np
from numpy import random
import random

In [ ]:
import torch

# Set device (CPU or GPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

In [ ]:

# Set device (CPU or GPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Define DQN Neural Network
class DQN(nn.Module):
    def __init__(self, input_dimensions, output_dimensions):
        super(DQN, self).__init__()
        self.fc1 = nn.Linear(input_dimensions, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, output_dimensions)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.fc3(x)

# Define Replay Memory
class Replay:
    def __init__(self, capacityN):
        self.tracker = deque(maxlen=capacityN)

    def push(self, s, a, r, s_, mission_accomplished):
        transition = (s, a, r, s_, mission_accomplished)
        self.tracker.append(transition)

    def Sampl(self, batch_len):
        transitions = random.sample(self.tracker, batch_len)
        states, actions, rewards, states_, missions_accomplished = [], [], [], [], []

        for transition in transitions:
            s, a, r, s_, mission_accomplished = transition
            states.append(s)
            actions.append(a)
            rewards.append(r)
            states_.append(s_)
            missions_accomplished.append(mission_accomplished)

        # Convert lists to numpy arrays
        states = np.vstack(states)  # Stack states into a 2D array
        actions = np.array(actions)
        rewards = np.array(rewards, dtype=np.float32)
        states_ = np.vstack(states_)  # Stack next states into a 2D array
        missions_accomplished = np.array(missions_accomplished, dtype=np.uint8)

        return states, actions, rewards, states_, missions_accomplished



In [ ]:
class DeterministicWarehouseRobotEnv(gym.Env):
    metadata = {'render.modes': []}

    def __init__(self):

        self.grid_size = 6 #6x6 grid

        self.start = [0, 0]
        self.pickup = [3, 3]
        self.end = [5, 5] # drop off location4

        self.agent_position = self.start.copy()

        self.obstacles = [(1, 3), (4, 2), (3,5),(4, 4)]
        self.picked_up_or_not = False



        self.actions = ["up", "down", "left", "right", "pick-up", "drop-off"]  # Up, Down, Left, Right, Pick-up, Drop-off

        self.observation_space = spaces.Dict({
            'agent_position': spaces.Tuple((spaces.Discrete(6), spaces.Discrete(6))), #coordinates could be any number between 0-5
            'agent_picked_up_or_not': spaces.Discrete(2) # 0 = not picked and 1 = picked
        })

        # Rewards
        self.reward_for_delivery = 100
        self.reward_pickup = 25
        self.reward_step = -1
        self.obstacle_penalty = -20
        self.invalid_Pickup_pentalty = -5
        self.invalid_Dropoff_pentalty = -5

        #self.q_table = {} not needed for part 1 checkpoint




    def reset(self):
        self.agent_position = self.start.copy()
        self.picked_up_or_not = False

        observation = {
            'agent_position': tuple(self.agent_position),
            'agent_picked_up_or_not': self.picked_up_or_not
        }
        return observation, {}




    def step(self, action):

      reward = self.reward_step
      mission_accomplished = False
      new_position = self.agent_position.copy()

      #actions
      if action == "up":  # Up
          new_position[0] -= 1
      elif action == "down":  # Down
          new_position[0] += 1
      elif action == "left":  # Left
          new_position[1] -= 1
      elif action == "right":  # Right
          new_position[1] += 1
      elif action == "pick-up":  # Pick-up
          if tuple(self.agent_position) == tuple(self.pickup) and not self.picked_up_or_not:
              self.picked_up_or_not = True
              reward += self.reward_pickup
          else:
              reward += self.invalid_Pickup_pentalty

      elif action == "drop-off":  # Drop-off
          if tuple(self.agent_position) == tuple(self.end) and self.picked_up_or_not:
              self.picked_up_or_not = False
              reward += self.reward_for_delivery
              mission_accomplished = True
          else:
              reward += self.invalid_Dropoff_pentalty


      # Check for collisions with obstacles or boundaries
      if tuple(new_position) in self.obstacles:
          reward += self.obstacle_penalty
      elif not (0 <= new_position[0] < 6 and 0 <= new_position[1] < 6):
          reward += self.obstacle_penalty
      else:
          self.agent_position = new_position



      # Observation
      observation = {
          'agent_position': tuple(self.agent_position),
          'agent_picked_up_or_not': self.picked_up_or_not
      }

      return observation, reward, mission_accomplished, False, {}




    def render(self):

      grid = np.zeros((6, 6))

      for obstacle in self.obstacles:
          grid[obstacle] = -1

      if not self.picked_up_or_not:
          grid[tuple(self.agent_position)] = 1
      else:
          grid[tuple(self.agent_position)] = 2

      grid[self.pickup[0], self.pickup[1]] = 3
      grid[self.end[0], self.end[1]] = 4

      plt.imshow(grid)
      plt.title('Warehouse Robot Environment')
      plt.show()


In [ ]:
BATCH_SIZE = 32
GAMMA = 0.99
EPS_START = 1.0
EPS_END = 0.01
EPS_DECAY = 0.995
TARGET_UPDATE = 10
LEARNING_RATE = 0.001
MEMORY_CAPACITY = 10000
NUM_EPISODES = 1000

In [ ]:
# Initialize environment, DQN, and replay memory
env = DeterministicWarehouseRobotEnv()
input_dimensions = 3  # (x, y, picked_up_or_not)
output_dimensions = 6  # 6 actions: up, down, left, right, pick-up, drop-off

primary_net = DQN(input_dimensions, output_dimensions).to(device)
target_net = DQN(input_dimensions, output_dimensions).to(device)
target_net.load_state_dict(primary_net.state_dict())
target_net.eval()

optimizer = optim.Adam(primary_net.parameters(), lr=LEARNING_RATE)
memory = Replay(MEMORY_CAPACITY)

# Epsilon-greedy action selection
def select_action(state, epsilon):
    if random.random() < epsilon:
        return random.randint(0, 5)  # Random action
    else:
        state_tensor = torch.FloatTensor(state).unsqueeze(0).to(device)
        return primary_net(state_tensor).argmax().item()

# Training step
def train_step():
    if len(memory.tracker) < BATCH_SIZE:
        return

    states, actions, rewards, states_, missions_accomplished = memory.Sampl(BATCH_SIZE)

    states = torch.FloatTensor(states).to(device)
    actions = torch.LongTensor(actions).to(device)
    rewards = torch.FloatTensor(rewards).to(device)
    states_ = torch.FloatTensor(states_).to(device)
    missions_accomplished = torch.FloatTensor(missions_accomplished).to(device)

    # Compute Q-values for current states
    Q_current = primary_net(states).gather(1, actions.unsqueeze(1))

    # Compute Q-values for next states using the target network
    Q_next = target_net(states_).max(1)[0].detach()
    Q_target = rewards + GAMMA * Q_next * missions_accomplished

    # Compute loss and update the primary network
    loss = F.mse_loss(Q_current, Q_target.unsqueeze(1))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

# Training loop
epsilon = EPS_START
rewards_per_episode = []

for episode in range(NUM_EPISODES):
    observation, _ = env.reset()
    state = np.array([*observation['agent_position'], observation['agent_picked_up_or_not']])  # Flatten state
    total_reward = 0
    done = False

    while not done:
        action = select_action(state, epsilon)
        observation_, reward, mission_accomplished, _, _ = env.step(env.actions[action])
        next_state = np.array([*observation_['agent_position'], observation_['agent_picked_up_or_not']])  # Flatten next state
        memory.push(state, action, reward, next_state, not mission_accomplished)
        state = next_state
        total_reward += reward

        if mission_accomplished:
            done = True

        train_step()

    # Decay epsilon
    epsilon = max(EPS_END, epsilon * EPS_DECAY)

    # Update target network
    if episode % TARGET_UPDATE == 0:
        target_net.load_state_dict(primary_net.state_dict())

    rewards_per_episode.append(total_reward)
    print(f"Episode {episode + 1}, Total Reward: {total_reward}, Epsilon: {epsilon:.2f}")



In [ ]:
# Plot rewards
import matplotlib.pyplot as plt

plt.plot(rewards_per_episode)
plt.xlabel('Episode')
plt.ylabel('Total Reward')
plt.title('Rewards per Episode')
plt.show()